runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: assets

- url: /bns-outlook-addin-manifest.xml
  static_files: bns-outlook-addin-manifest.xml
  upload: bns-outlook-addin-manifest.xml
  
- url: /favicon.ico
  static_files: assets/icons/favicon.ico
  upload: assets/icons/favicon.ico

- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.json$
- node_modules/
- resources/
